name: telegram_cli
description: Telegram bot api request api from cli.
version: 0.0.1
homepage: https://github.com/azkadev/telegram_client/tree/main/dart/telegram_client/docs
repository: https://github.com/azkadev/telegram_client/tree/main/dart/telegram_client
issue_tracker: https://github.com/azkadev/telegram_client/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  switchscript: ^0.0.3
  telegram_client: ^0.0.3

executables:
  telegram: telegram