name: telegram_client
description: Telegram Client Lightweight, blazing and Highly customizable for make application telegram based tdlib, mtproto, or bot api and support server side.
version: 0.3.91
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/telegram_client/tree/main/dart/telegram_client
issue_tracker: https://github.com/azkadev/telegram_client/issues 
documentation: https://telegram-client.vercel.app/
funding:
  - https://github.com/sponsors/azkadev/

# publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0

dependencies:
  ffi: ^2.0.1
  galaxeus_lib: ^0.0.36
  http: ^0.13.5
  telegram_bot_api: ^0.0.2
  telegram_mtproto: ^0.0.0
  telegram_tdlib: ^0.0.0
  universal_io: ^2.0.4
  web_ffi: ^0.7.2

executables:
  tg: tg_cli
