name: telegram_client
description: Telegram Client Lightweight, blazing and Highly customizable for make application telegram based tdlib, mtproto, or bot api and support server side.
version: 0.3.71
homepage: https://github.com/azkadev/telegram_client/wiki
repository: https://github.com/azkadev/telegram_client/tree/main/dart/telegram_client
issue_tracker: https://github.com/azkadev/telegram_client/issues
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0

dependencies:
  ffi: ">=1.1.2 <=2.0.1" 
  galaxeus_lib:
    path: /home/hexaminate/Documents/HEXAMINATE/app/galaxeus/packages/dart/galaxeus_lib/
  # galaxeus_lib: ^0.0.27
  hexaminate: ^0.1.4
  http: ^0.13.4
  universal_io: ^2.0.4
  web_ffi: ^0.7.2

executables:
  tg_cli: tg_cli
