name: mtproto
description: telegram client mtproto dart flutter.
version: 0.0.0
homepage: https://github.com/azkadev/telegram_client/tree/main/dart/mtproto/docs
repository: https://github.com/azkadev/telegram_client/tree/main/dart/mtproto
issue_tracker: https://github.com/azkadev/telegram_client/issues


environment:
  sdk: '>=2.16.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
